name: acel_giro_mesure
description: "Acelerometer, giroscope tool"
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sensors_plus: ^7.0.0
  sqflite: ^2.4.2
  path: ^1.9.1
  flutter_bloc: ^9.1.0
  freezed_annotation: ^3.0.0
  fl_chart: ^1.1.1
  share_plus: ^10.1.4
  path_provider: ^2.1.5
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.2.5
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  assets:
    - assets/icon.jpg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpg"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon.jpg"
